// Laura's weekly roundup.
//
// Every ~7 days, Laura reads the club's recent feed, names the Honor
// Roll winners, and roasts the week. The post is generated by Claude
// (Haiku — same model that writes the per-ride blog), cached in Vercel
// Blob, and rendered on the homepage as "From Laura · This Week."
//
// Generation strategy:
//   - Read the most recent stored roundup. If it's <7 days old, return
//     it unchanged. Cheap, deterministic, no API hit on every render.
//   - If it's stale (or there's nothing), build a fresh prompt from the
//     current club activities + awarded Honor Roll, call Claude, store
//     the result, return it.
//   - On any failure (missing API key, network, parse), return the
//     stored copy if any — never block the page render on Anthropic.
//
// The prompt is structured to keep Laura on-voice (dry, sarcastic,
// affectionate) and to ensure she names at least 4 distinctions so the
// post reads as a roll-call, not a generic recap.

import Anthropic from "@anthropic-ai/sdk";
import { put, list } from "@vercel/blob";
import type { ClubActivity } from "./club";
import type { AwardedDistinction } from "./honor-roll";

const BLOB_KEY = "laura-roundup.json";
const REFRESH_AFTER_MS = 6.5 * 24 * 60 * 60 * 1000; // ~weekly
const MODEL = "claude-haiku-4-5";

export interface WeeklyRoundup {
  title: string;
  body: string;
  /** ISO timestamp — used to decide if we should regenerate. */
  generatedAt: string;
  /** Distinction IDs we asked Laura to name, in case the UI wants to cross-link. */
  awardedIds: string[];
}

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

// ─── Storage helpers ───────────────────────────────────────────

async function loadLatest(): Promise<WeeklyRoundup | null> {
  try {
    const blobs = await list({ prefix: BLOB_KEY });
    if (blobs.blobs.length === 0) return null;
    // Sort by uploadedAt desc so we always read the most recent.
    blobs.blobs.sort(
      (a, b) =>
        new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    );
    const res = await fetch(blobs.blobs[0].url, { cache: "no-store" });
    if (!res.ok) return null;
    return (await res.json()) as WeeklyRoundup;
  } catch (err) {
    console.warn("[laura-roundup] load failed:", err);
    return null;
  }
}

async function save(roundup: WeeklyRoundup): Promise<void> {
  try {
    await put(BLOB_KEY, JSON.stringify(roundup, null, 2), {
      access: "public",
      contentType: "application/json",
      allowOverwrite: true,
    });
  } catch (err) {
    console.error("[laura-roundup] save failed:", err);
  }
}

// ─── Prompt construction ──────────────────────────────────────

function buildPrompt(
  activities: ClubActivity[],
  awards: AwardedDistinction[]
): string {
  // Roll up the feed into one-line summaries so Laura has facts to
  // work with but no overwhelming detail.
  const rideLines = activities
    .filter((a) => (a.sport_type || a.type || "").toLowerCase().includes("ride"))
    .slice(0, 20)
    .map((a) => {
      const mi = Math.round(a.distance / 1609.34);
      const ft = Math.round(a.total_elevation_gain * 3.28084);
      return `- ${a.athlete.firstname} ${a.athlete.lastname[0]}.: "${a.name}" — ${mi} mi, ${ft} ft`;
    })
    .join("\n");

  const awardLines = awards
    .map(
      (a) =>
        `- ${a.label}: ${a.winnerName} (${a.statText}) — "${a.description}"`
    )
    .join("\n");

  return `You are Laura Ryder, Cycling Hawai'i's club manager, bookkeeper, and resident roaster. You write a weekly roundup post that runs on the homepage and names every Honor Roll winner.

VOICE
- Dry. Sarcastic. Affectionate underneath. Never mean.
- You believe cycling is great but takes itself too seriously, and your job is to puncture that lightly.
- You write in clean prose. No emoji. No hashtags. No exclamation points.
- You are NOT a hype account. You are a bookkeeper with strong opinions.
- Lanterne Rouge gets celebrated, not pitied — last across the line is still across the line.

INPUTS

Recent rides in the club feed (≤20):
${rideLines || "(no recent rides — quiet week)"}

This week's Honor Roll winners:
${awardLines || "(no awards this week)"}

WRITING RULES
- Length: 180-260 words. Tight prose. No padding.
- Name at least 4 winners by full name and distinction. Make each naming feel earned, not listed.
- Don't repeat the stat numbers verbatim from the inputs — translate them ("a small mountain's worth of climbing," "a number of miles only a Rouleur would log").
- Open with a single short sentence that sets the week's mood. Not a date.
- Close with a Laura line — something that nudges readers to ride, tag #cyclinghawaii, or quietly suffer.
- Plain text only. No markdown. No headings. Just paragraphs separated by blank lines.
- DO NOT prefix the body with the date.

OUTPUT FORMAT
Return ONLY a JSON object, no preamble:
{
  "title": "<6-10 word title in your voice>",
  "body": "<the post itself, plain paragraphs>"
}`;
}

// ─── Public API ────────────────────────────────────────────────

/**
 * Return the current weekly roundup. Generates a new one if the stored
 * copy is older than ~7 days, or if nothing is stored yet. Safe to call
 * from a server component during ISR render.
 *
 * Caller is expected to pre-filter activities to the cycling feed and
 * to have already computed the Honor Roll for the same window.
 */
export async function getWeeklyRoundup(
  activities: ClubActivity[],
  awards: AwardedDistinction[]
): Promise<WeeklyRoundup | null> {
  const existing = await loadLatest();
  const now = Date.now();

  // Fresh enough — serve from cache.
  if (
    existing &&
    now - new Date(existing.generatedAt).getTime() < REFRESH_AFTER_MS
  ) {
    return existing;
  }

  // Need a fresh one. If anything goes wrong, fall back to existing.
  if (!process.env.ANTHROPIC_API_KEY) {
    console.warn("[laura-roundup] no ANTHROPIC_API_KEY — serving stored copy");
    return existing;
  }

  try {
    const prompt = buildPrompt(activities, awards);
    const res = await client.messages.create({
      model: MODEL,
      max_tokens: 800,
      messages: [{ role: "user", content: prompt }],
    });

    // The SDK's ContentBlock union includes citations etc. on TextBlock;
    // narrow by type and access `.text` directly.
    const text = res.content
      .filter((b) => b.type === "text")
      .map((b) => (b as { text: string }).text)
      .join("\n")
      .trim();

    // Extract the JSON object from the response. Claude sometimes wraps
    // it in code fences despite instructions; strip those defensively.
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.warn("[laura-roundup] no JSON in response, keeping existing");
      return existing;
    }
    const parsed = JSON.parse(jsonMatch[0]) as {
      title?: string;
      body?: string;
    };
    if (!parsed.title || !parsed.body) {
      console.warn("[laura-roundup] malformed JSON, keeping existing");
      return existing;
    }

    const roundup: WeeklyRoundup = {
      title: parsed.title.trim(),
      body: parsed.body.trim(),
      generatedAt: new Date().toISOString(),
      awardedIds: awards.map((a) => a.id),
    };
    await save(roundup);
    return roundup;
  } catch (err) {
    console.error("[laura-roundup] generation failed:", err);
    return existing;
  }
}
